import type { VideoItem } from "./VideoRow";

export const Videos: Array<VideoItem> = [
  {
    author: "Allen Vailliencourt",
    date: "2021-10-29",
    href: "https://goteleport.com/resources/videos/sharpen-security-skills-open-source/",
    labels: [
      "teleport",
      "SSH",
      "access plane",
      "infrastructure",
      "audit log",
      "kubernetes",
      "security",
    ],
    title: "Sharpen Your Security Skills with Open Source!",
    videoId: "_DUuHJKWD8I",
  },
  {
    author: "Jonathon Canada",
    date: "2021-09-29",
    href: "https://goteleport.com/resources/videos/applying-least-privilege/",
    labels: ["access", "teleport", "kubernetes", "zero trust", "rbac"],
    title: "Applying Least Privilege in Kubernetes",
    videoId: "JWUjV6wWIJ4",
  },
  {
    author: "Roman Tkachenko, Ben Arent",
    date: "2021-08-19",
    href: "https://goteleport.com/resources/videos/mongodb-access-webinar/",
    labels: ["teleport", "mongodb", "access plane", "certificates", "security"],
    title: "MongoDB Access Webinar",
    videoId: "BiDdSqCLwNg",
  },
  {
    author: "Stephen Faig, Steven Martin",
    date: "2021-06-30",
    href: "https://goteleport.com/resources/videos/securing-access-to-fleets/",
    labels: [
      "teleport",
      "postgres",
      "mysql",
      "database access",
      "unified access plane",
    ],
    title: "Securing Access to Fleets of Postgres & MySQL",
    videoId: "5Rsn__RLazM",
  },
  {
    author: "Steven Martin, Ben Arent",
    date: "2021-06-30",
    href: "https://goteleport.com/resources/videos/tokens-tls-teleport/",
    labels: [
      "teleport",
      "tokens",
      "SSH",
      "tls",
      "access plane",
      "certificates",
      "kubernetes",
      "automation",
    ],

    title: "Tokens, TLS, and Teleport",
    videoId: "ffNi9FsRmFw",
  },
  {
    author: "Ben Arent",
    date: "2021-05-20",
    href: "https://goteleport.com/resources/guides/adding-your-first-database-to-teleport/",
    labels: ["access control", "database access", "teleport"],
    title: "Adding Your First Database to Teleport",
    videoId: "PCYyTecSzCY",
  },
  {
    author: "Ben Arent",
    date: "2021-05-12",
    href: "https://goteleport.com/resources/videos/hardened-teleport-access/",
    labels: [
      "teleport",
      "hardened teleport access",
      "SSH",
      "infosec",
      "unified access plane",
      "osi",
      "shared responsibility",
      "hardware tokens",
      "authorization rules",
      "mfa",
    ],
    title: "Hardened Teleport Access",
    videoId: "VpaNxwxLLJw",
  },
  {
    author: "Roman Tkachenko",
    date: "2021-04-14",
    href: "https://goteleport.com/resources/videos/application-access/",
    labels: [
      "teleport",
      "teleport application access",
      "SSH",
      "infosec",
      "unified access plane",
      "applications",
      "audit log",
    ],
    title: "Teleport Application Access",
    videoId: "xOLKVJnrBT0",
  },
  {
    author: "Roman Tkachenko, Anadelia Fadeev",
    date: "2021-02-18",
    href: "https://goteleport.com/resources/videos/introducing-database-access/",
    labels: [
      "teleport",
      "SSH",
      "infosec",
      "access plane",
      "applications",
      "audit log",
      "database access",
      "kubernetes",
    ],
    title: "Introducing Teleport Database Access",
    videoId: "wNCpYIDG1qM",
  },
  {
    author: "Virag Mody",
    date: "2021-01-14",
    href: "https://goteleport.com/resources/videos/top-10-hacks-last-decade/",
    labels: [
      "teleport",
      "SSH",
      "infosec",
      "breaches",
      "applications",
      "kubernetes",
      "hacks",
      "RBAC",
      "segmentation",
      "secrets",
    ],
    title: "Top 10 Hacks of the Past Decade",
    videoId: "YUEQnuWo2KQ",
  },
  {
    author: "Ben Arent, Mark Herring",
    date: "2020-12-16",
    href: "https://goteleport.com/resources/videos/teleport-cloud-overview-demo/",
    labels: [
      "teleport",
      "SSH",
      "infosec",
      "teleport cloud",
      "applications",
      "audit",
      "kubernetes",
      "SOC2",
      "FedRAMP",
      "reverse tunnel",
    ],
    title: "Teleport Cloud Demo and Overview",
    videoId: "1jhKOtBinm4",
  },
  {
    author: "Ben Arent, Greg Chase",
    date: "2020-11-19",
    href: "https://goteleport.com/resources/videos/teleport-unified-access-plane-explainer/",
    labels: ["teleport"],
    title: "Teleport Access Plane | Application Access Demo",
    videoId: "macHAfsBqqA",
  },
  {
    author: "Ben Arent",
    date: "2020-10-07",
    href: "https://goteleport.com/resources/videos/ssh-compliance-visibility/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS", "ZeroTrust"],
    title: "Teleport 4.4 SSH Compliance and Visibility",
    videoId: "x5iAv17PDWg",
  },
  {
    author: "Steven Martin, Vance McCarthy",
    date: "2020-09-28",
    href: "https://goteleport.com/resources/videos/RBAC-for-SSH-and-Kubernetes-Access/",
    labels: [
      "teleport",
      "SSH",
      "infosec",
      "RBAC",
      "kubernetes",
      "OSS",
      "enterprise",
    ],
    title: "iDevNews: RBAC for SSH and Kubernetes Access with Teleport",
    videoId: "cO256wi-BEI",
  },
  {
    author: "Ben Arent",
    date: "2020-09-23",
    href: "https://goteleport.com/resources/videos/workflow-access-pageduty-slack/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS", "ZeroTrust"],
    title: "Teleport Access Workflows - Slack & PagerDuty",
    videoId: "onyoT8BCSe0",
  },
  {
    author: "Virag Mody",
    date: "2020-09-21",
    href: "https://goteleport.com/resources/videos/secure-access-for-cloud-and-aws/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS", "ZeroTrust"],
    title: "Securely Access Compute Resources in Cloud",
    videoId: "CTewLcYpSx0",
  },
  {
    author: "Gus Luxton, Charlene O’Hanlon",
    date: "2020-09-09",
    href: "https://goteleport.com/resources/videos/ssh-industry-best-practice/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS", "ZeroTrust"],
    title: "SSH Access - Industry Best Practices",
    videoId: "2vVEmxp0eys",
  },
  {
    author: "Hunter Madison, Mark Herring",
    date: "2020-09-02",
    href: "https://goteleport.com/resources/videos/secure-developer-access-at-decisiv/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS", "ZeroTrust"],
    title: "Secure Developer Access at Decisv",
    videoId: "qNKsG3z_qJU",
  },
  {
    author: "Ev Kontsevoy, Gus Luxton, Jack Naglieri",
    date: "2020-08-19",
    href: "https://goteleport.com/resources/videos/ssh-best-practice/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS", "ZeroTrust"],
    title: "Industry Best Practices for SSH Access",
    videoId: "hM3LZiLgagQ",
  },
  {
    author: "Ev Kontsevoy",
    date: "2020-08-05",
    href: "https://goteleport.com/resources/videos/webinar-kubernetes-audit-logging/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS", "k8s"],
    title: "Best Practices in Kubernetes Audit Logging",
    videoId: "XPpOZ_hiy1g",
  },
  {
    author: "Teleport",
    date: "2020-07-28",
    href: "https://goteleport.com/resources/videos/devops-zero-trust-hype/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS", "ZeroTrust"],
    title: "Zero Trust - Separating out Fact from Fiction",
    videoId: "fNpCkm-MqiE",
  },
  {
    author: "Gus Luxton",
    date: "2020-07-16",
    href: "https://goteleport.com/resources/videos/teleport-43-demo/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS"],
    title: "Teleport 4.3 | Demo and Presentation",
    videoId: "UIK3b42MHmM",
  },
  {
    author: "Ev Kontsevoy",
    date: "2020-07-10",
    href: "https://goteleport.com/resources/videos/teleport-43-shortdemo/",
    labels: ["teleport"],
    title: "Teleport | 5 minute demo",
    videoId: "DUlTAlEJr5w",
  },
  {
    author: "Gus Luxton",
    date: "2019-10-09",
    href: "https://goteleport.com/resources/videos/teleport-webinar/",
    labels: ["teleport", "SSH", "kubernetes", "Certificate Authority"],
    title: "Teleport for Privileged Access Management",
    videoId: "UPqESjphF40",
  },
  {
    author: "Taylor Wakefield",
    date: "2019-09-20",
    href: "https://goteleport.com/resources/videos/open-core-vs-proprietary-saas-ocs-2019/",
    labels: ["open core", "gravitational", "gravity"],
    title: "Open Core vs Proprietary SaaS",
    videoId: "9Vj51JqQgzA",
  },
  {
    author: "Sasha Klizhentas",
    date: "2019-07-16",
    href: "https://goteleport.com/resources/videos/teleport-k8s-webinar/",
    labels: ["teleport", "SSH", "kubernetes", "Certificate Authority"],
    title: "Best Practices for Access Control with SSH & Kubernetes",
    videoId: "OBbx3axz_5A",
  },
  {
    author: "Gravitational",
    date: "2019-03-12",
    href: "https://goteleport.com/resources/videos/teleport-overview/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS"],
    title: "Video Overview",
    videoId: "vpl8ArKyzfQ",
  },
  {
    author: "Taylor Wakefield",
    date: "2018-10-02",
    href: "https://goteleport.com/resources/videos/teleport-v3-demo/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS"],
    title: "Kubernetes Support Demo",
    videoId: "zIuZHYO_cDI",
  },
  {
    author: "Abraham Ingersoll",
    date: "2018-01-16",
    href: "https://goteleport.com/resources/videos/teleport-clusters/",
    labels: ["teleport", "SSH", "infosec", "PAM", "Sales", "OSS"],
    title: "Trusted Clusters in Teleport",
    videoId: "jrQowMb54gs",
  },
  {
    author: "Taylor Wakefield",
    date: "2016-09-06",
    href: "https://goteleport.com/resources/videos/teleconsole-intro/",
    labels: ["teleconsole", "SSH", "PAM", "Sales", "OSS"],
    title: "Introduction to Teleconsole",
    videoId: "R8CnrnquS_s",
  },
  {
    author: "Travis Gary",
    date: "2021-12-02",
    href: "https://goteleport.com/esources/videos/infra-as-code-not-jira-tickets/",
    labels: ["infrastructure", "jira", "security", "audit", "teleport"],
    title: "Infra-as-Code Not Jira Tickets to Pass Audits",
    videoId: "8XEzepW_Jtk",
  },
  {
    author: "Jonathon Canada",
    href: "https://goteleport.com/resources/videos/mfa-everything/",
    title: "MFA Everything",
    date: "2021-12-27",
    labels: ["mfa", "sso", "security", "teleport", "access", "kubernetes"],
    videoId: "H0_PfKS53gg",
  },
  {
    author: "Cody J. Brown, Colin Wood",
    href: "https://goteleport.com/resources/videos/reduce-complexity-increase-security/",
    title: "Reduce Complexity to Increase Security",
    date: "2022-01-12",
    labels: [
      "teleport",
      "SSH",
      "access plane",
      "infrastructure",
      "audit log",
      "kubernetes",
      "security",
    ],
    videoId: "fvm2MIK1ZmE",
  },
  {
    author: "Jonathon Canada",
    href: "https://goteleport.com/resources/videos/secure-RBAC-SSO-for-kubernetes/",
    title: "Secure RBAC/SSO for Kubernetes with Teleport",
    date: "2021-01-19",
    labels: ["teleport", "rbac", "sso", "github", "kubernetes", "access plane"],
    videoId: "NgGFDpnuxUc",
  },
];
